###############################
# DEFAULT 
###############################
enabled: true
developer: false
scheduler: true
worker: false
namespace: root-supervisor
name: supervisor
replicas: 1
image:
    name: spaceone/supervisor
    version: latest
imagePullPolicy: IfNotPresent

resources: {}
#     scheduler: 
#         requests:
#             memory: "128Mi"
#             cpu: "25m"
#         limits:
#             memory: "256Mi"
#             cpu: "50m"

# Overwrite database
database: {}

# Overwrite application config
#application: {}

# Overwrite scheduler config
#application_scheduler: {}
application_scheduler:
    NAME: root
    HOSTNAME: root-supervisor.root
    BACKEND: KubernetesConnector
    CONNECTORS:
        RepositoryConnector:
            endpoint:
                v1: grpc://repository.spaceone.svc.cluster.local:50051
        PluginConnector:
            endpoint:
                v1: grpc://plugin.spaceone.svc.cluster.local:50051
        KubernetesConnector:
            namespace: root-supervisor
            start_port: 50051
            end_port: 50052
            headless: true
            replica:
                inventory.Collector: 1

##########################
# local sidecar
##########################
sidecar:
    redis:
        image:
            name: redis
            version: latest
            imagePullPolicy: IfNotPresent
        resources: {}
        #     requests:
        #         memory: "128Mi"
        #         cpu: "25m"
        #     limits:
        #         memory: "256Mi"
        #         cpu: "50m"
    scheduler: {}

##########################
# Local volumes
##########################
volumes:
    - name: timezone
      hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
    - name: log-volume
      emptyDir: {}

#######################
# global variable
#######################
global:
    shared: {}
    supervisor_namespace: root-supervisor
    supervisor:
        sidecar: []
        volumes: []

####################################
# pod spec (append more pod spec)
# example nodeSelect
#
# pod:
#   spec:
#     nodeSelector:
#       application: my-node-group
####################################
pod:
    spec: {}