REMOTE_URL:
- file:///opt/spaceone/supervisor/config/shared.yaml
- file:///opt/spaceone/supervisor/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: localhost
      port: 6379
      db: 1
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/supervisor.log
  HANDLERS: {}
  CONNECTORS:
    IdentityConnector:
      endpoint:
        v1: grpc://identity:50051
    PluginConnector:
      endpoint:
        v1: grpc://plugin:50051
    RepositoryConnector:
      endpoint:
        v1: grpc://repository:50051
#    KubernetesConnector:
#        namespace: root-supervisor
#        start_port: 50051
#        end_port: 50052
#        headless: true
#        replica:
#            inventory.collector: 4

  QUEUES:
    default_q:
      backend: spaceone.core.queue.redis_queue.RedisQueue
      host: localhost
      port: 6379
      channel: supervisor_queue

  SCHEDULERS:
    sync:
      backend: spaceone.supervisor.scheduler.sync_scheduler.SyncScheduler
      queue: default_q
      interval: 10

#  NAME: root
#  HOSTNAME: root-supervisor.svc.cluster.local
#  BACKEND: KubernetesConnector
